apiVersion: apps/v1
kind: Deployment
metadata:
  name: epicauth
  labels:
    app.kubernetes.io/name: epicauth
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: epicauth
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: epicauth
    spec:
      serviceAccountName: epicauth
      containers:
      - name: epicauth
        image: epicauth
        imagePullPolicy: Always
        command:
        - /contour-authserver
        args:
        - epic
        - --address=:9443
        - --tls-ca-path=/tls/ca.crt
        - --tls-cert-path=/tls/tls.crt
        - --tls-key-path=/tls/tls.key
        ports:
        - name: auth
          containerPort: 9443
          protocol: TCP
        volumeMounts:
        - name: tls
          mountPath: /tls
          readOnly: true
        resources:
          limits:
            memory: 90Mi
      volumes:
      - name: tls
        secret:
          secretName: epicauth
---
apiVersion: v1
kind: Service
metadata:
  name: epicauth
  labels:
    app.kubernetes.io/name: epicauth
spec:
  ports:
  - name: auth
    protocol: TCP
    port: 9443
    targetPort: 9443
  selector:
    app.kubernetes.io/name: epicauth
  type: ClusterIP
