apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- serviceaccount.yaml
- certificate.yaml
- role.yaml
- rolebinding.yaml

images:
- name: htpasswd
  newName: 192.168.1.80:5000/epic/contour-authserver
  newTag: v0.0.0-dev0
