.set-tag: &set-tag
- |
  if [ -n "${CI_COMMIT_TAG}" ] ; then
    # If this build is from a git tag, use that as the docker tag.
    export TAG_SPECIFIC="${CI_COMMIT_TAG}"
  else
    # If this build is from a branch, use the name and sha as the
    # docker tag.
    export TAG_SPECIFIC="${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}"
  fi
  export IMG=registry.gitlab.com/acnodal/epic/contour-authserver:${TAG_SPECIFIC}

docker:
  image: docker:20.10.10
  services:
  - docker:20.10.10-dind

  before_script:
  - *set-tag
  - apk add make git wget tar
  # Install kustomize
  - wget --no-verbose -O - https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv4.0.1/kustomize_v4.0.1_linux_amd64.tar.gz | tar -C /usr/local/bin -xzf -
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

  script:
  - make VERSION=${TAG_SPECIFIC} IMG=${IMG} docker-build docker-push
  - cd config/epic
  - kustomize edit set image htpasswd=${IMG}
  - kustomize build . > ../../deploy/contour-authserver-epic.yaml

  artifacts:
    paths:
      - config/epic
      - deploy/*.yaml
